# .travis.yml
language: node_js
node_js:
  - '8.1.0'
script: npm run travis
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libuv1 openssl-dev zlib1g-dev
notifications:
  email: false
deploy:
  - provider: npm
    email: jim@vigour.io
    api_key: ${NPM_TOKEN}
    on:
      branch: master